package com.example.util

import com.example.data.model.AppLanguage

object Localization {

    fun getString(key: String, language: AppLanguage): String {
        val faMap = mapOf(
            // Navigation
            "home" to "خانه",
            "library" to "کتابخانه",
            "playlists" to "پلی‌لیست",
            "search" to "جستجو",
            "wrapped" to "خلاصه من (رپد)",
            "nav_home" to "خانه",
            "nav_library" to "کتابخانه",
            "nav_playlists" to "پلی‌لیست",
            "nav_search" to "جستجو",
            "nav_wrapped" to "خلاصه من (رپد)",
            "nav_settings" to "تنظیمات",

            // Common & Actions
            "play" to "پخش",
            "pause" to "توقف",
            "next" to "بعدی",
            "previous" to "قبلی",
            "shuffle" to "پخش تصادفی",
            "repeat" to "تکرار",
            "queue" to "صف پخش",
            "lyrics" to "متن ترانه",
            "equalizer" to "اکولایزر",
            "sleep_timer" to "تایمر خواب",
            "settings" to "تنظیمات",
            "share" to "اشتراک‌گذاری",
            "close" to "بستن",
            "cancel" to "انصراف",
            "save" to "ذخیره",
            "delete" to "حذف",
            "search_hint" to "جستجوی آهنگ، خواننده، آلبوم...",
            "favorites" to "علاقه‌مندی‌ها",
            "recent" to "به تازگی پخش شده",
            "all_songs" to "تمام آهنگ‌ها",
            "playlists" to "پلی‌لیست",
            "new_playlist" to "پلی‌لیست جدید",
            "create_playlist" to "ایجاد پلی‌لیست جدید",
            "new_playlist_hint" to "نام پلی‌لیست را وارد کنید...",
            "playlists_and_genres" to "پلی‌لیست‌ها و دسته‌بندی‌ها",
            "tracks" to "آهنگ",
            "artists" to "هنرمندان",
            "albums" to "آلبوم‌ها",
            "genres" to "سبک‌ها",
            "collections" to "مجموعه‌ها",
            "change_artwork" to "تغییر کاور آهنگ",
            "select_from_gallery" to "انتخاب تصویر از گالری",
            "remove_artwork" to "حذف کاور فعلی",
            "artwork_updated" to "کاور آهنگ با موفقیت به‌روز شد",
            "skin_vinyl" to "گرامافون آنالوگ لوکس",
            "skin_barbie" to "باربی دریم (Barbie Glow)",
            "skin_batman" to "شوالیه تاریکی (Batman Knight)",
            "skin_last_of_us" to "لست آف آز (The Last of Us)",
            "vip_profile_title" to "پروفایل و وضعیت اشتراک شما",
            "vip_plan_annual_only" to "اشتراک ۱ ساله VIP (۳۵,۰۰۰ تومان)",
            "vip_days_remaining" to "روز باقی‌مانده",
            "vip_hours_remaining" to "ساعت باقی‌مانده",
            "start_tutorial" to "راهنمای تعاملی برنامه",

            // Home
            "aura_music" to "موزیک پلیر آئورا",
            "audio_environment" to "فضای صوتی فراگیر",
            "currently_playing" to "در حال پخش",
            "quick_play" to "پخش سریع",
            "wrapped_banner_title" to "خلاصه شنیداری شما آماده است!",
            "wrapped_banner_desc" to "مشاهده آمار شنیداری ماهانه و سالانه",
            "open_wrapped" to "مشاهده رپد",
            "featured_recommendation" to "پیشنهاد اختصاصی",

            // Wrapped
            "wrapped_title" to "خلاصه موسیقی شما",
            "wrapped_subtitle" to "تحلیل هوشمند و واقعی از سلیقه شنیداری شما",
            "monthly_wrapped" to "خلاصه ماهانه",
            "yearly_wrapped" to "خلاصه سالانه",
            "select_period" to "انتخاب دوره",
            "total_listening_time" to "مجموع زمان گوش‌دادن",
            "minutes" to "دقیقه",
            "hours" to "ساعت",
            "tracks_played" to "آهنگ‌های پخش شده",
            "skips_count" to "تعداد رد کردن آهنگ (اسکیپ)",
            "listening_streak" to "رکورد روزهای متوالی پخش",
            "days" to "روز",
            "top_songs" to "۵ آهنگ برتر شما",
            "top_artists" to "هنرمندان برگزیده",
            "top_albums" to "آلبوم‌های محبوب",
            "top_genres" to "سبک‌های شاخص",
            "favorite_time" to "زمان طلایی گوش‌دادن",
            "days_with_aura" to "همراهی با آئورا",
            "audio_personality" to "شخصیت شنیداری شما",
            "share_wrapped" to "اشتراک‌گذاری کارت خلاصه",
            "no_history_yet" to "هنوز داده شنیداری کافی ثبت نشده است. شروع به گوش‌دادن کنید!",
            "completion_rate" to "درصد تکمیل ترک‌ها",

            // Settings
            "preferences" to "تنظیمات و شخصی‌سازی",
            "theme_appearance" to "تم و جلوه‌های بصری",
            "accent_palette" to "پالت رنگ تأکیدی",
            "language_settings" to "زبان برنامه (Language)",
            "visualizer_dsp" to "اکولایزر بصری و هاله نوری",
            "visualizer_presets" to "حالت‌های پیش‌فرض",
            "audio_sensitivity" to "حساسیت پاسخ صوتی",
            "halo_glow" to "میزان درخشش هاله و بلوم",
            "engine_fps" to "نرخ نوسازی انجین بصری",
            "auto_color" to "استخراج خودکار رنگ از کاور آهنگ",
            "lyrics_typography" to "تنظیمات متن ترانه و کارائوکه",
            "display_mode" to "حالت نمایش متن",
            "font_size" to "اندازه قلم",
            "karaoke_highlight" to "هایلایت کلمه به کلمه کارائوکه",
            "audio_hardware" to "تنظیمات پیشرفته صدا و هدفون",
            "crossfade_duration" to "مدت زمان محو تدریجی (Crossfade)",
            "gapless_playback" to "پخش بدون وقفه (Gapless)",
            "pause_on_disconnect" to "توقف خودکار هنگام قطع هدفون",
            "duck_volume" to "کاهش ملایم صدا هنگام زنگ/اعلان",
            "haptic_feedback" to "بازخورد لرزشی (هپتیک)",
            "performance_mode" to "حالت بهینه‌سازی مصرف باتری",
            "reduced_motion" to "کاهش انیمیشن‌ها",
            "storage_cache" to "مدیریت حافظه و داده‌ها",
            "clear_cache" to "پاک‌سازی حافظه موقت کاورها",
            "clear_history" to "پاک کردن تاریخچه شنیداری و رپد",
            "rescan_library" to "اسکن مجدد فایل‌های صوتی دستگاه",
            "backup_restore" to "پشتیبان‌گیری و بازگردانی",
            "export_backup" to "خروجی فایل پشتیبان (JSON)",
            "import_backup" to "بازگردانی فایل پشتیبان",
            "feedback_section" to "بازخورد و ارتباط با پشتیبانی",
            "send_feedback" to "ارسال نظر، گزارش باگ یا پیشنهاد",

            // Feedback Dialog
            "feedback_dialog_title" to "ارسال نظر و بازخورد",
            "feedback_type" to "نوع پیام",
            "type_bug" to "گزارش باگ و اشکال",
            "type_feature" to "درخواست قابلیت جدید",
            "type_general" to "نظرات و پیشنهادات",
            "feedback_message_hint" to "متن نظر یا توضیحات مشکل را در اینجا بنویسید...",
            "feedback_sending_to" to "ارسال مستقیم به: parsaghorbani0000@gmail.com",
            "feedback_submit" to "ارسال با ایمیل",
            "feedback_copy" to "کپی در حافظه کلیپ‌بورد",
            "feedback_success" to "برنامه ایمیل باز شد و اطلاعات پیام آماده ارسال است.",
            "feedback_copied" to "متن بازخورد به همراه مشخصات دستگاه در کلیپ‌بورد کپی شد.",

            // 15 New Features Strings
            "on_this_day_title" to "امروز در تاریخ شنیداری شما",
            "weekly_recap_title" to "گزارش هفتگی شنیداری شما",
            "welcome_back" to "خوش برگشتید به آئورا",
            "intelligent_shuffle" to "شافل هوشمند بر اساس انرژی و تمپو",
            "shuffle_mode_off" to "پخش ترتیبی",
            "shuffle_mode_random" to "پخش تصادفی ساده",
            "shuffle_mode_smart" to "شافل هوشمند آئورا",
            "focus_mode" to "حالت تمرکز و مطالعه",
            "focus_mode_desc" to "پخش اختصاصی موزیک‌های بی‌کلام و محیط مینیمال",
            "app_icon_theme" to "آیکون اختصاصی هماهنگ با تم",
            "app_icon_change_dialog" to "برای اعمال آیکون جدید، ممکن است آیکون در صفحه اصلی گوشی به‌روزرسانی شود. آیا مایل به تغییر هستید؟",
            "continuous_mix" to "میکس پیوسته دی‌جی (Continuous Mix)",
            "continuous_mix_desc" to "کراس‌فید هوشمند و هم‌پوشان بر اساس تمپو و سطح انرژی",
            "hearing_profile" to "کالیبراسیون پروفایل شنوایی",
            "hearing_profile_desc" to "تنظیم فرکانس‌های صوتی متناسب با گوش شما",
            "unlocked_styles" to "استایل‌های اختصاصی Now Playing",
            "vinyl_style" to "صفحه وینیل و گرامافون کلاسیک",
            "duplicates_manager" to "بهینه‌ساز و مدیریت فایل‌های تکراری",
            "share_story_card" to "اشتراک‌گذاری کارت تصویری برای استوری",
            "start_focus" to "شروع حالت تمرکز",
            "calibrate_hearing" to "شروع تست شنوایی",

            // Track Actions & Deletion
            "play_now" to "پخش فوری",
            "play_next" to "پخش بعد از این",
            "add_to_queue" to "افزودن به انتهای صف",
            "add_to_playlist" to "افزودن به پلی‌لیست",
            "remove_from_playlist" to "حذف از این پلی‌لیست",
            "edit_metadata" to "ویرایش اطلاعات و متادیتا",
            "delete_track" to "حذف دائمی آهنگ",
            "delete_track_title" to "حذف آهنگ از برنامه",
            "delete_track_confirm" to "آیا مطمئن هستید که می‌خواهید این آهنگ را حذف کنید؟ این آهنگ با انیمیشن محو و متلاشی شدن از لیست حذف خواهد شد.",
            "delete_playlist_title" to "حذف پلی‌لیست",
            "delete_playlist_confirm" to "آیا از حذف این پلی‌لیست اطمینان دارید؟",
            "playlist_details" to "پلی‌لیست و قطعات",
            "play_all" to "پخش همه",
            "empty_playlist" to "هنوز آهنگی در این پلی‌لیست قرار نگرفته است.",

            // Features Showcase Guide
            "features_guide_btn" to "راهنمای امکانات و قابلیت‌های آئورا",
            "features_guide_desc" to "معرفی موتور صوتی Hi-Fi، تم‌های ۳ بعدی، لیریکس زنده و اکولایزر",
            "features_showcase" to "راهنمای امکانات و قابلیت‌های آئورا",
            "features_showcase_desc" to "معرفی موتور صوتی Hi-Fi، تم‌های ۳ بعدی، لیریکس زنده و اکولایزر",
            "features_guide_title" to "امکانات و قابلیت‌های برجسته آئورا",
            "features_guide_subtitle" to "طراحی شده برای عاشقان موسیقی با بالاترین کیفیت پردازش و زیبایی بصری"
        )

        val enMap = mapOf(
            // Navigation
            "home" to "Home",
            "library" to "Library",
            "playlists" to "Playlists",
            "search" to "Search",
            "wrapped" to "Wrapped",
            "nav_home" to "Home",
            "nav_library" to "Library",
            "nav_playlists" to "Playlists",
            "nav_search" to "Search",
            "nav_wrapped" to "Wrapped",
            "nav_settings" to "Settings",

            // Common & Actions
            "play" to "Play",
            "pause" to "Pause",
            "next" to "Next",
            "previous" to "Previous",
            "shuffle" to "Shuffle",
            "repeat" to "Repeat",
            "queue" to "Queue",
            "lyrics" to "Lyrics",
            "equalizer" to "Equalizer",
            "sleep_timer" to "Sleep Timer",
            "settings" to "Settings",
            "share" to "Share",
            "close" to "Close",
            "cancel" to "Cancel",
            "save" to "Save",
            "delete" to "Delete",
            "search_hint" to "Search tracks, artists, albums...",
            "favorites" to "Favorites",
            "recent" to "Recently Played",
            "all_songs" to "All Songs",
            "playlists" to "Playlists",
            "create_playlist" to "Create New Playlist",
            "new_playlist_hint" to "Enter playlist name...",
            "playlists_and_genres" to "Playlists & Soundscapes",
            "tracks" to "Tracks",
            "artists" to "Artists",
            "albums" to "Albums",
            "genres" to "Genres",

            // Home
            "aura_music" to "AURA MUSIC",
            "audio_environment" to "Audio Environment",
            "currently_playing" to "CURRENTLY PLAYING",
            "quick_play" to "QUICK PLAY",
            "wrapped_banner_title" to "Your Listening Recap is Ready!",
            "wrapped_banner_desc" to "Explore your Monthly & Yearly Wrapped stats",
            "open_wrapped" to "View Wrapped",
            "featured_recommendation" to "Sonic Frequency Pick",

            // Wrapped
            "wrapped_title" to "Listening Wrapped",
            "wrapped_subtitle" to "Real-time authentic analysis of your musical universe",
            "monthly_wrapped" to "Monthly Wrapped",
            "yearly_wrapped" to "Yearly Wrapped",
            "select_period" to "Select Timeframe",
            "total_listening_time" to "Total Listening Time",
            "minutes" to "min",
            "hours" to "hours",
            "tracks_played" to "Tracks Played",
            "skips_count" to "Total Skips",
            "listening_streak" to "Listening Streak",
            "days" to "Days",
            "top_songs" to "Top 5 Anthems",
            "top_artists" to "Top Artists",
            "top_albums" to "Top Albums",
            "top_genres" to "Dominant Genres",
            "favorite_time" to "Prime Listening Hour",
            "days_with_aura" to "Days with Aura",
            "audio_personality" to "Audio Personality",
            "share_wrapped" to "Share Recap Card",
            "no_history_yet" to "No listening sessions recorded yet. Start playing your music!",
            "completion_rate" to "Completion Rate",

            // Settings
            "preferences" to "PREFERENCES",
            "theme_appearance" to "Theme & Dark Atmosphere",
            "accent_palette" to "Accent Color Palette",
            "language_settings" to "App Language (زبان)",
            "visualizer_dsp" to "Visualizer & Ambient Halo",
            "visualizer_presets" to "Presets",
            "audio_sensitivity" to "Audio Sensitivity",
            "halo_glow" to "Halo Glow & Bloom",
            "engine_fps" to "Visualizer Engine FPS",
            "auto_color" to "Auto Color From Artwork",
            "lyrics_typography" to "Lyrics Display & Karaoke",
            "display_mode" to "Display Mode",
            "font_size" to "Font Size",
            "karaoke_highlight" to "Karaoke Word-Level Highlight",
            "audio_hardware" to "Audio DSP & Hardware",
            "crossfade_duration" to "Crossfade Duration",
            "gapless_playback" to "Gapless Playback",
            "pause_on_disconnect" to "Pause on Headphone Disconnect",
            "duck_volume" to "Duck Volume on Call/Notification",
            "haptic_feedback" to "Haptic Feedback",
            "performance_mode" to "Battery Saver Mode",
            "reduced_motion" to "Reduced Motion",
            "storage_cache" to "Storage & Cache Management",
            "clear_cache" to "Clear Artwork & Image Cache",
            "clear_history" to "Clear Playback History & Wrapped Stats",
            "rescan_library" to "Trigger MediaStore Rescan",
            "backup_restore" to "Backup & Restore",
            "export_backup" to "Export Backup (JSON)",
            "import_backup" to "Import Backup",
            "feedback_section" to "Feedback & Support",
            "send_feedback" to "Send Feedback, Bug Report, or Feature Idea",

            // Feedback Dialog
            "feedback_dialog_title" to "Feedback & Bug Report",
            "feedback_type" to "Category",
            "type_bug" to "Bug Report",
            "type_feature" to "Feature Request",
            "type_general" to "General Feedback",
            "feedback_message_hint" to "Describe your suggestion or issue in detail...",
            "feedback_sending_to" to "Directly sending to: parsaghorbani0000@gmail.com",
            "feedback_submit" to "Send via Email",
            "feedback_copy" to "Copy to Clipboard",
            "feedback_success" to "Email client opened with pre-filled feedback report.",
            "feedback_copied" to "Feedback report & device info copied to clipboard.",

            // 15 New Features Strings
            "on_this_day_title" to "On This Day in Your History",
            "weekly_recap_title" to "Your Weekly Music Recap",
            "welcome_back" to "Welcome Back to Aura",
            "intelligent_shuffle" to "Intelligent Shuffle (Energy & Tempo)",
            "shuffle_mode_off" to "In Order",
            "shuffle_mode_random" to "Classic Random Shuffle",
            "shuffle_mode_smart" to "Aura Intelligent Flow",
            "focus_mode" to "Focus & Study Mode",
            "focus_mode_desc" to "Instrumental tracks only with distraction-free layout",
            "app_icon_theme" to "Theme-Matching App Icon",
            "app_icon_change_dialog" to "Updating the app icon might update the icon on your launcher home screen. Continue?",
            "continuous_mix" to "Continuous DJ Mix",
            "continuous_mix_desc" to "Dynamic overlapping crossfades modulated by BPM & energy",
            "hearing_profile" to "Hearing Calibration Profile",
            "hearing_profile_desc" to "Fine-tune audio frequencies tailored to your ears",
            "unlocked_styles" to "Exclusive Now Playing Styles",
            "vinyl_style" to "Classic Vinyl Turntable",
            "duplicates_manager" to "Duplicate Audio Optimizer",
            "share_story_card" to "Share Visual Story Card",
            "start_focus" to "Start Focus Session",
            "calibrate_hearing" to "Start Hearing Test",

            // Track Actions & Deletion
            "play_now" to "Play Now",
            "play_next" to "Play Next",
            "add_to_queue" to "Add to Queue",
            "add_to_playlist" to "Add to Playlist",
            "remove_from_playlist" to "Remove from Playlist",
            "edit_metadata" to "Edit Metadata",
            "delete_track" to "Delete Track",
            "delete_track_title" to "Delete Track from App",
            "delete_track_confirm" to "Are you sure you want to permanently delete this track? It will be removed with a fantasy disintegration animation.",
            "delete_playlist_title" to "Delete Playlist",
            "delete_playlist_confirm" to "Are you sure you want to delete this playlist?",
            "playlist_details" to "Playlist Tracks",
            "play_all" to "Play All",
            "empty_playlist" to "No tracks in this playlist yet.",

            // Features Showcase Guide
            "features_guide_btn" to "Aura Features & Capabilities Guide",
            "features_guide_desc" to "Explore Hi-Fi Audio DSP, 3D Themes, Live Lyrics & Visualizers",
            "features_showcase" to "Aura Features & Capabilities Guide",
            "features_showcase_desc" to "Explore Hi-Fi Audio DSP, 3D Themes, Live Lyrics & Visualizers",
            "features_guide_title" to "Aura Features & Architecture",
            "features_guide_subtitle" to "Crafted for audiophiles with uncompromised sound fidelity and visual aesthetics"
        )

        return if (language == AppLanguage.PERSIAN) {
            faMap[key] ?: enMap[key] ?: key
        } else {
            enMap[key] ?: key
        }
    }
}
